"""empty message

Revision ID: 21060e79509b
Revises: 
Create Date: 2024-10-01 22:05:39.699668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21060e79509b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('localisation', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metiers')
    op.drop_table('departements')
    # ### end Alembic commands ###
