"""empty message

Revision ID: ed25d48694ec
Revises: 514476d3bdb0
Create Date: 2024-10-02 07:00:56.015829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed25d48694ec'
down_revision = '514476d3bdb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departements', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('localisation',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('metiers', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
        batch_op.alter_column('nom',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metiers', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('nom',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)

    with op.batch_alter_table('departements', schema=None) as batch_op:
        batch_op.alter_column('localisation',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
